<?php

declare(strict_types=1);

namespace App\Model;

/**
 * Job DTO
 *
 * Readonly data transfer object representing a job record.
 */
readonly class Job
{
    public function __construct(
        public ?int $id,
        public int $organizationId,
        public string $jobDate,
        public string $jobStatus,
        public int $warehouseId,
        public int $customerId,
        public ?int $quotationId,
        public string $jobReferenceNo,
        public string $jobNo,
        public int $jobSeq,
        public int $salesPerson,
        public string $currency,
        public float $exchangeRate,
        public string $transportMode,
        public string $shipmentType,
        public int $jobOwner,
        public ?string $tags,
        public ?string $services,
        public int $csAgent,
        public string $incoterm,
        public ?string $email,
        public float $supplierRate,
        public float $estimatedNetProfit,
        public float $estimatedInvoiceAmount,
        public string $etd,
        public string $eta,
        public int $carrier,
        public ?string $vesselName,
        public string $vesselDepartureDate,
        public ?string $flightNo,
        public string $flightDepartureDate,
        public string $jobCompletionDate,
        public ?string $paymentTerms,
        public ?string $hawb,
        public ?string $mawb,
        public float $estimatedCostAmount,
        public string $declarationNo,
        public float $grossWeight,
        public float $volumeWeight,
        public float $chargeableWeight,
        public int $noOfPieces,
        public int $commodityType,
        public int $noOfContainers,
        public string $insuranceNeeded,
        public int $containerType,
        public string $temperatureControlRequired,
        public ?string $containerNumber,
        public ?string $specialComments,
        public int $landingCountry,
        public int $landingPort,
        public int $loadingPlace,
        public ?string $billingCity,
        public ?string $billingState,
        public ?string $billingCode,
        public int $billingCountry,
        public int $destinationCountry,
        public int $destinationPort,
        public ?string $fdp,
        public ?string $shippingCity,
        public ?string $shippingState,
        public ?string $shippingCode,
        public int $shippingCountry,
        public ?string $subject,
        public ?string $termsAndConditions,
        public float $grandSubtotal,
        public string $grandDiscountType,
        public float $grandDiscountTypeValue,
        public float $grandDiscountAmount,
        public float $grandAfterDiscount,
        public ?string $customerNotes,
        public float $grandTax,
        public float $grandTotal,
        public string $happyCustomer,
        public ?string $unhappyReason,
        public string $shipmentOnTime,
        public ?string $referral,
        public ?string $notes,
        public int $booksCustomerId,
        public int $quoteId,
        public int $projectId,
        public ?string $modifiedBy,
        public ?string $customerType,
        public ?string $approvedTime,
        public ?string $approvedTimeResubmission,
        public bool $publish,
        public bool $isActive,
        public ?string $createdAt,
        public ?string $updatedAt,
        public ?int $updatedBy,
        public int $createdBy,
        public ?string $pdf
    ) {
    }

    /**
     * Convert DTO to array (snake_case keys matching DB columns)
     */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'organization_id' => $this->organizationId,
            'job_date' => $this->jobDate,
            'job_status' => $this->jobStatus,
            'warehouse_id' => $this->warehouseId,
            'customer_id' => $this->customerId,
            'quotation_id' => $this->quotationId,
            'job_ref_no' => $this->jobReferenceNo,
            'job_no' => $this->jobNo,
            'job_seq' => $this->jobSeq,
            'sales_person' => $this->salesPerson,
            'currency' => $this->currency,
            'exchange_rate' => $this->exchangeRate,
            'transport_mode' => $this->transportMode,
            'shipment_type' => $this->shipmentType,
            'job_owner' => $this->jobOwner,
            'tags' => $this->tags,
            'services' => $this->services,
            'cs_agent' => $this->csAgent,
            'incoterm' => $this->incoterm,
            'email' => $this->email,
            'supplier_rate' => $this->supplierRate,
            'estimated_net_profit' => $this->estimatedNetProfit,
            'estimated_invoice_amount' => $this->estimatedInvoiceAmount,
            'etd' => $this->etd,
            'eta' => $this->eta,
            'carrier' => $this->carrier,
            'vessel_name' => $this->vesselName,
            'vessel_departure_date' => $this->vesselDepartureDate,
            'flight_no' => $this->flightNo,
            'flight_departure_date' => $this->flightDepartureDate,
            'job_completion_date' => $this->jobCompletionDate,
            'payment_terms' => $this->paymentTerms,
            'hawb' => $this->hawb,
            'mawb' => $this->mawb,
            'estimated_cost_amount' => $this->estimatedCostAmount,
            'declaration_no' => $this->declarationNo,
            'gross_weight' => $this->grossWeight,
            'volume_weight' => $this->volumeWeight,
            'chargeable_weight' => $this->chargeableWeight,
            'no_of_pieces' => $this->noOfPieces,
            'commodity_type' => $this->commodityType,
            'no_of_containers' => $this->noOfContainers,
            'insurance_needed' => $this->insuranceNeeded,
            'container_type' => $this->containerType,
            'temperature_control_required' => $this->temperatureControlRequired,
            'container_number' => $this->containerNumber,
            'special_comments' => $this->specialComments,
            'landing_country' => $this->landingCountry,
            'landing_port' => $this->landingPort,
            'loading_place' => $this->loadingPlace,
            'billing_city' => $this->billingCity,
            'billing_state' => $this->billingState,
            'billing_code' => $this->billingCode,
            'billing_country' => $this->billingCountry,
            'destination_country' => $this->destinationCountry,
            'destination_port' => $this->destinationPort,
            'fdp' => $this->fdp,
            'shipping_city' => $this->shippingCity,
            'shipping_state' => $this->shippingState,
            'shipping_code' => $this->shippingCode,
            'shipping_country' => $this->shippingCountry,
            'subject' => $this->subject,
            'terms_and_conditions' => $this->termsAndConditions,
            'grand_subtotal' => $this->grandSubtotal,
            'grand_discount_type' => $this->grandDiscountType,
            'grand_discount_type_value' => $this->grandDiscountTypeValue,
            'grand_discount_amount' => $this->grandDiscountAmount,
            'grand_after_discount' => $this->grandAfterDiscount,
            'customer_notes' => $this->customerNotes,
            'grand_tax' => $this->grandTax,
            'grand_total' => $this->grandTotal,
            'happy_customer' => $this->happyCustomer,
            'unhappy_reason' => $this->unhappyReason,
            'shipment_on_time' => $this->shipmentOnTime,
            'referral' => $this->referral,
            'notes' => $this->notes,
            'books_customer_id' => $this->booksCustomerId,
            'quote_id' => $this->quoteId,
            'project_id' => $this->projectId,
            'modified_by' => $this->modifiedBy,
            'customer_type' => $this->customerType,
            'approved_time' => $this->approvedTime,
            'approved_time_resubmission' => $this->approvedTimeResubmission,
            'publish' => $this->publish ? 1 : 0,
            'is_active' => $this->isActive ? 1 : 0,
            'created_at' => $this->createdAt,
            'updated_at' => $this->updatedAt,
            'updated_by' => $this->updatedBy,
            'created_by' => $this->createdBy,
            'pdf' => $this->pdf
        ];
    }
}
